# why numpy(list vs numpy)

In [35]:
# import numpy as np
import time
import sys
SIZE = 1000000
l1 = range(SIZE)
l2 = range(SIZE)
a1=np.arange(SIZE)
a2=np.arange(SIZE)

# python list
start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print("python list took: ",(time.time()-start)*1000)
# numpy array
start= time.time()
result = a1 + a2
print("numpy took: ", (time.time()-start)*1000)

python list took:  187.4687671661377
numpy took:  15.624284744262695


# basic code

In [36]:
import numpy as np
a=np.arange(12)
print(a)
print(a.ndim)
print(a.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
1
(12,)


In [37]:
b=a.reshape(3,4)
print(b)
print(b.shape)
print(b.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
2


In [38]:
print("sum of all : ",b.sum())
print("Min of all : ",b.min())
print("Max of all : ",b.max())
print("Mean of all : ",b.mean())
print("Row sum : ",b.sum(axis=1))
print("Column sum of all : ",b.sum(axis=0))

sum of all :  66
Min of all :  0
Max of all :  11
Mean of all :  5.5
Row sum :  [ 6 22 38]
Column sum of all :  [12 15 18 21]


In [39]:
k=np.arange(11,30)
print(k)
k1=np.arange(11,20,3)
print(k1)

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
[11 14 17]


In [40]:
k2=np.arange(1,2,0.3)
print(k2)
k3=np.arange(1,2,0.01)
print(k3)
print(len(k3))

[1.  1.3 1.6 1.9]
[1.   1.01 1.02 1.03 1.04 1.05 1.06 1.07 1.08 1.09 1.1  1.11 1.12 1.13
 1.14 1.15 1.16 1.17 1.18 1.19 1.2  1.21 1.22 1.23 1.24 1.25 1.26 1.27
 1.28 1.29 1.3  1.31 1.32 1.33 1.34 1.35 1.36 1.37 1.38 1.39 1.4  1.41
 1.42 1.43 1.44 1.45 1.46 1.47 1.48 1.49 1.5  1.51 1.52 1.53 1.54 1.55
 1.56 1.57 1.58 1.59 1.6  1.61 1.62 1.63 1.64 1.65 1.66 1.67 1.68 1.69
 1.7  1.71 1.72 1.73 1.74 1.75 1.76 1.77 1.78 1.79 1.8  1.81 1.82 1.83
 1.84 1.85 1.86 1.87 1.88 1.89 1.9  1.91 1.92 1.93 1.94 1.95 1.96 1.97
 1.98 1.99]
100


In [41]:
m=np.linspace(1,2,10)
print(m)

[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]


In [42]:
k=[[1,2],[3,4]]
a=np.array(k)
print(a)
b=np.array([[5,6],[7,8]])
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [43]:
print(a+3)
print(a>3)
print(a+b)
print(a.dot(b))

[[4 5]
 [6 7]]
[[False False]
 [False  True]]
[[ 6  8]
 [10 12]]
[[19 22]
 [43 50]]


In [44]:
print(np.sqrt(189))

13.74772708486752


In [45]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [47]:
for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [48]:
for x in np.nditer(a, order='C'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [49]:
for x in np.nditer(a, order='F'):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [50]:
for x in np.nditer(a, flags=['external_loop'],order='F'):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [51]:
for x in np.nditer(a, op_flags=['readwrite']):
    x[...] = x * x

In [52]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [53]:
b = np.arange(3, 15, 4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [54]:
for x, y in np.nditer([a,b]):
    print (x,y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11


In [55]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])